### ISSUE TITLE
Change via shape to round

### ISSUE THREAD

**Issue by shulter** [awesomeshield/Awesome-Shield-PCB#1]

**Comment by fionapalmer** [comment]
@aShure I've been using a 1mm radius miter to do this. Is that a reasonable turning radius?

**Comment by shulter** [comment]
I was thinking about the via pads :) They seem to be squared. You can change the via shape of all the vias simultaneously with the command line.

**Comment by fionapalmer** [comment]
Right! Thanks for clarifying. Somehow I read 'via' as 'trace'. Oops. I'll make sure all the traces are normal straight edges on 45 degree turns, and make sure the vias are all round :-)

**Comment by fionapalmer** [comment]
done.
