### ISSUE TITLE
A3 is connected to GND instead of potentiometer

### ISSUE THREAD

**Issue by shulter** [awesomeshield/Awesome-Shield-PCB#10]
check middle pin of potentiometer, it's NC right now.

**Comment by fionapalmer** [comment]
good catch! I connected A3 to the middle pin of the pot on branches `master` , `CPver2` , `CPvar6`

@cwjpalmer: remember to update this on branch `issue11` if merging that branch into main

**Comment by fionapalmer** [comment]
@aShure do you think I should connect the large mounting holes to GND, or leave them as NC?

**Comment by shulter** [comment]
Connecting to GND is fine, use thermals to make it easy to solder - lots of thermal mass.

**Comment by fionapalmer** [comment]
@aShure I'm having a bit of a tough time getting eagle to connect those pads to the GND net. Is there any reason not to leave them NC (as they are now, and as the part in the Sparkfun library is configured)? If there's nothing bad about leaving them as is, I'll do that.

**Comment by shulter** [comment]
No problem just leave them like that. FYI for future endeavors: If you
can't manage to connect the pin in the library part, you can always
route a wire with the GND net (use the name command) to a pin manually
as a hack and ignore the DRC error for that pin then.

**Comment by fionapalmer** [comment]
Great! I'll leave it, and that's a really good trick to know. Thanks for sharing the tip :-)
