### ISSUE TITLE
Toggle Switch Pads

### ISSUE THREAD

**Issue by fionapalmer** [awesomeshield/Awesome-Shield-PCB#14]
@aShure I added 1mm to the outside edges of the toggle switch pads to make hand soldering easier. Initially the pads were exactly the same as the landing area of the feet. Do you think this will be okay for reflow, in terms of surface tension pull to one side or the other if there's an uneven heat distribution?

**Comment by shulter** [comment]
It will be if you remove the thermals from the pads (uncheck Thermals at the part level) and route the GND wires manually, normal to the pads

**Comment by shulter** [comment]
I just tried that and reversed it again. I think it doesn't make a difference at all because of the soldermask surrounding all the pads.
