### ISSUE TITLE
Use 5V instead of IOREF

### ISSUE THREAD

**Issue by fionapalmer** [awesomeshield/Awesome-Shield-PCB#33]
I think it would be better to use the 5V pin to supply power to the potentiometer and the photodiode, rather than the IOREF pin.

**Comment by shulter** [comment]
Why do you think it would be better?

**Comment by fionapalmer** [comment]
@aShure My thinking was that it's a good idea to keep the IOREF pin unused so that people can use it to adjust the IO reference voltage if they want. Is there an advantage to using it over the 5V to supply power to the analog components?

Maybe using the AREF pin to supply power to the analog components is actually a better way to go? That way if you change the AREF voltage you're using, you still get a full range of readings from the analog components.

**Comment by shulter** [comment]
The IOREF pin can't be adjusted by the user, it is exactly for this purpose, to have a full scale reading on the ADC. The IOREF pin signals to the shield what kind of host board is used. 

Using 5V hardwired is not a good idea because host boards might run on 3V3.

**Comment by shulter** [comment]
The AREF pin is meant to be used as an input, not a reference output. Different application.

**Comment by fionapalmer** [comment]
Okay great! Thanks @aShure I misunderstood, and it sounds like we should keep using the IOREF pin.
