### ISSUE TITLE
Component Labeling on Silk Screen

### ISSUE THREAD

**Issue by fionapalmer** [awesomeshield/Awesome-Shield-PCB#35]
Components (excluding resistors and headers) should have enough space next to them for labels. Space for labels should be on the side closest to the end of the board that pin 0 and pin A5 are on on an Arduino Uno pinout. The photodiode resistor should be placed far enough from spaces that labels will be in to avoid ambiguity of any labels.

4 pin connectors ("Grove ports") should have enough space around them for either a label or a shape to be drawn around them on the silk screen.

**Comment by fionapalmer** [comment]
@aShure FYI the font we're going to use for component labels on the silk screen will be the summer font, which you can see in the Awesome Shield styleguide http://awesomeshield.com/styleguide (it's the H1 font). I'm pointing this out because it's pretty tall and skinny, so the aspect ratio will effect the component spacing.

**Comment by fionapalmer** [comment]
Here's a sample graphic that has the component names in the correct font.

![silkscreen text sample](https://cloud.githubusercontent.com/assets/6217632/16694492/e6acf1a4-453a-11e6-8715-5e9ea5faef0c.png)

**Comment by shulter** [comment]
Needs to be done after the E-CAD, Eagle can't render fonts. It's also horrible at dithering/aliasing/interpolating anything. 
I suggest submitting Eagle sources plus rendered masks (export form Eagle, modify with graphic editor) to manufacturer.
Tipp: Use the top, bottom and guide layers as low opacity overlays when working on the silkscreen design in a graphic editor, makes it easy to spot collisions like vias.

**Comment by fionapalmer** [comment]
added bitmap top silkscreen in V0.60 release
