### ISSUE TITLE
Via too close to pad?

### ISSUE THREAD

**Issue by fionapalmer** [awesomeshield/Awesome-Shield-PCB#38]
There's a via next to one of the pads for port 2. The via's pad is within the solder mask pull-back area of the port's pad. Ie. there will be exposed copper from the via right next to the port. I don't think this is an issue since the via is routed to the pad. But it seemed unusual so I'm pointing it out just in case.
![screen shot 2016-07-25 at 13 52 38 gmt 2](https://cloud.githubusercontent.com/assets/6217632/17100665/3ba1aa28-5270-11e6-89fd-01f0a339da9c.png)

**Comment by shulter** [comment]
that looks fine. via-in-pad is sometimes default for BGA assemblies :) you can make the via smaller or the restring smaller or move the via if you want!
