### ISSUE TITLE
GND via close to trace

### ISSUE THREAD

**Issue by fionapalmer** [awesomeshield/Awesome-Shield-PCB#39]
There's a GND via less than one trace-width away from a trace. It's the via that's right next to port 1.
![screen shot 2016-07-25 at 14 18 35 gmt 2](https://cloud.githubusercontent.com/assets/6217632/17101081/c860eb3e-5272-11e6-8c22-112e134ee812.png)

**Comment by shulter** [comment]
Good catch, I'll move it. It's within the design rules (the isolation distance is enough) so I didn't catch it.

**Comment by fionapalmer** [comment]
Thanks! 👍
