### ISSUE TITLE
Route potentiometer to IOREF instead of a fixed power rail

### ISSUE THREAD

**Issue by shulter** [awesomeshield/Awesome-Shield-PCB#8]
That is the actual purpose of IOREF, a value of 3.3V won't be a full ADC reading on a 5V Arduino if the pot is fixed to 3.3V max.

**Comment by shulter** [comment]
Same might make sense for other parts..

**Comment by fionapalmer** [comment]
Great call! I think I should do the same with the thermistor. I'm not sure about the photodiode, though. What do you think @aShure ?

**Comment by shulter** [comment]
Yes. Simply all devices that feed into the ADC should have the same voltage output that the controller runs on. Less than the controller's voltage is possible too, but one would lose resolution and a scale in software is needed then.

**Comment by fionapalmer** [comment]
great! I opened a new issue for the other ADC components
